gm/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import misc, calculators, searches, lists, details, prints, faq

app_name = 'gm'
urlpatterns = [
    path('', misc.IndexView.as_view(), name='index'),
    path('about/', misc.AboutView.as_view(), name='about'),
    path('ai_generator/', cache_page(0)(misc.generateAI), name='ai_generator'),
    path('ai_generator/<codename>/', misc.generateAI, name='ai_informations'),
    path('ajax/autocomplete.json', misc.AutocompleteView.as_view(), name='autocomplete'),
    path('ajax/theme', misc.SetTheme.as_view(), name='set_theme'),
    
    path('weapon/', lists.WeaponListView.as_view(), name='weapon_list'),
    path('module/', lists.ModuleListView.as_view(), name='module_list'),
    path('effect/', lists.EffectListView.as_view(), name='effect_list'),
    path('overdrive/', lists.OverdriveListView.as_view(), name='overdrive_list'),
    path('enhancement/', lists.EnhancementListView.as_view(), name='enhancement_list'),
    path('armour/', lists.ArmourListView.as_view(), name='armour_list'),
    path('division/', lists.DivisionListView.as_view(), name='division_list'),
    path('arcana/', lists.ArcanaListView.as_view(), name='arcana_list'),
    path('crest/', lists.CrestListView.as_view(), name='crest_list'),
    path('archetype/', lists.ArchetypeListView.as_view(), name='archetype_list'),
    path('great_deed/', lists.GreatDeedListView.as_view(), name='great_deed_list'),
    path('heroic-ability/', lists.HeroicAbilityListView.as_view(), name='heroic_ability_list'),
    path('vehicle/', lists.VehicleListView.as_view(), name='vehicle_list'),
    path('style/', lists.StyleListView.as_view(), name='style_list'),
    path('trauma/', lists.TraumaListView.as_view(), name='trauma_list'),
    path('mecha/', lists.MechaArmourListView.as_view(), name='mecha_list'),
    path('npc-ability/', lists.NonPlayerCharacterAbilityListView.as_view(), name='npc_ability_list'),
    path('twin_ability/', lists.ArmourTwinAbilityListView.as_view(), name='twin_list'),
    path('ultimate_aptitude/', lists.UltimateAptitudeListView.as_view(), name='ultimate_list'),
    
    path('weapon/<int:pk>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<int:pk>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<int:pk>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<int:pk>/', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<int:pk>/', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/<int:pk>/', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<int:pk>/', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<int:pk>/', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<int:pk>/', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('heroic-ability/<int:pk>/', details.HeroicAbilityDetailView.as_view(), name='heroic_ability_detail'),
    path('vehicle/<int:pk>/', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('trauma/<int:pk>/', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('ultimate_aptitude/<int:pk>/', details.UltimateAptitudeDetailView.as_view(), name='ultimate_detail'),
    
    path('weapon/<slug:slug>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<slug:slug>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<slug:slug>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<slug:slug>/', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<slug:slug>/', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/classified', details.ArmourClassifiedView.as_view(), name='armour_unknown'),
    path('armour/<slug:slug>/', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<slug:slug>/', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<slug:slug>/', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<slug:slug>/', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('heroic-ability/<slug:slug>/', details.HeroicAbilityDetailView.as_view(), name='heroic_ability_detail'),
    path('archetype/<slug:slug>/', details.ArchetypeDetailView.as_view(), name='archetype_detail'),
    path('crest/<slug:slug>/', details.CrestDetailView.as_view(), name='crest_detail'),
    path('vehicle/<slug:slug>/', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('style/<slug:slug>/', details.StyleDetailView.as_view(), name='style_detail'),
    path('trauma/<slug:slug>/', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('mecha/classified', details.MechaArmourClassifiedView.as_view(), name='mecha_unknown'),
    path('mecha/<slug:slug>/', details.MechaArmourDetailView.as_view(), name='mecha_detail'),
    path('npc-ability/<slug:slug>/', details.NonPlayerCharacterAbilityDetailView.as_view(), name='npc_ability_detail'),
    path('ultimate_aptitude/<slug:slug>/', details.UltimateAptitudeDetailView.as_view(), name='ultimate_detail'),
    
    path('longbow_calculator/', calculators.LongbowCalculatorView.as_view(), name='longbow_calculator'),
    path('weapon-calculator/', calculators.WeaponCalculatorView.as_view(), name='weapon_calculator'),
    
    path('faq/v1/', faq.QuestionV1ListView.as_view(), name='faqv1'),
    path('faq/v1.5/', faq.QuestionV1Dot5ListView.as_view(), name='faqv1.5'),
    
    path('search/', searches.search, name='search'),
    
    path('print/weapon/', prints.WeaponPrintListView.as_view(), name='print_weapon'),
    path('print/module/', prints.ModulePrintListView.as_view(), name='print_module'),
    path('print/overdrive/', prints.OverdrivePrintListView.as_view(), name='print_overdrive'),
    path('print/enhancement/', prints.EnhancementPrintListView.as_view(), name='print_enhancement'),
    path('print/trauma/', prints.TraumaPrintListView.as_view(), name='print_trauma'),
    
    # Retrocomp
    path('skill/', lists.HeroicSkillListRedirectView.as_view(), name='skill_list'),
    path('skill/<int:pk>/', details.HeroicSkillDetailRedirectView.as_view(), name='skill_detail'),
    path('skill/<slug:slug>/', details.HeroicSkillDetailRedirectView.as_view(), name='skill_detail'),
    path('stance/', lists.StanceListRedirectView.as_view(), name='stance_list'),
    path('stance/<slug:slug>/', details.StanceDetailRedirectView.as_view(), name='stance_detail'),
    path('npc_capacity/', lists.NonPlayerCharacterCapacityListRedirectView.as_view(), name='npc_capacity_list'),
    path('npc_capacity/<slug:slug>/', details.NonPlayerCharacterCapacityDetailRedirectView.as_view(), name='npc_capacity_detail'),
    
]

knight_master_overview/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static

from .views import account, martor

urlpatterns = [
    path('camelot/', admin.site.urls),
    path('martor/uploader/', martor.markdown_uploader, name="markdown_uploader_page"),
    path('martor/', include('martor.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('api/', include('api.urls')),
    path('accounts/login/', account.JointLoginSignupView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
]

gm_urls = ([
    path('', include('gm.urls')),
], 'gm')


virtualtable_urls = ([
    path('', include('virtualtable.urls')),
], 'virtualtable')

urlpatterns += i18n_patterns(
    path('', include('gm.urls')),
    path('virtualtable/', include('virtualtable.urls')),
    path('api/', include('api.urls')),
    path('users/', include('users.urls')),
    prefix_default_language=True
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

virtualtable/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'virtualtable'
urlpatterns = [
    path('create/', cache_page(0)(views.CreateTableView.as_view()), name='vt_create'),
    path('list/', cache_page(0)(views.ListTableView.as_view()), name='vt_list'),
    path('detail/<int:pk>/', cache_page(0)(views.DetailTableView.as_view()), name='vt_detail'),
    path('delete/<int:pk>/', cache_page(0)(views.DeleteTableView.as_view()), name='vt_delete'),
    path('update/<int:pk>/', cache_page(0)(views.UpdateTableView.as_view()), name='vt_update'),
    path('help/', cache_page(0)(views.HelpTableView.as_view()), name='vt_help'),
    
    path('logo/<int:vt>/<int:faction>', cache_page(0)(views.UpdateLogoFactionView.as_view()), name='vt_faction_update'),
    
    path('test/', cache_page(0)(views.TestView.as_view()), name='vt_test'),
    
    path('consent/<int:pk>', cache_page(0)(views.ConsentTableView.as_view()), name='vt_consent'),
    path('join/<str:invitation_token>/', cache_page(0)(views.PlayerJoinTableView.as_view()), name='join'),
    
    path('ajax/default_consent.json', views.DefaultConsentValues.as_view(), name='vt_default_consent'),
]

virtualtable/templates/virtualtable/character_creation.1.html
{% extends 'virtualtable/base.html' %}

{% load static %}
{% load martortags %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load gm_extras %}

{% block content %}
<form method="post">
    <h1 class="text-center">Création de personnage</h1>
    {% csrf_token %}
    {{ form.token|as_crispy_field }}
    <div class="row">
        <div class="col">
            {{ form.automatically_computed|as_crispy_field }}
        </div>
    </div>
    
    
    <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="character-tab" data-toggle="tab" href="#character" role="tab" aria-controls="character" aria-selected="true">{% trans "Personnage" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="arcana-tab" data-toggle="tab" href="#arcana" role="tab" aria-controls="arcana" aria-selected="false">{% trans "Arcanes" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="stats-tab" data-toggle="tab" href="#stats" role="tab" aria-controls="stats" aria-selected="false">{% trans "Aspects & caractéristiques" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="equipment-tab" data-toggle="tab" href="#equipment" role="tab" aria-controls="equipment" aria-selected="false">{% trans "Équipements" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="note-tab" data-toggle="tab" href="#note" role="tab" aria-controls="note" aria-selected="false">{% trans "Notes" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="background-tab" data-toggle="tab" href="#background" role="tab" aria-controls="background" aria-selected="false">{% trans "Background" %}</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="character" role="tabpanel" aria-labelledby="character-tab">
            <div class="row">
                <div class="col-8">
                    <div class="row">
                        <div class="col-6">
                            {{ form.name|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.nickname|as_crispy_field }}
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-6">
                            {{ form.archetype|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.great_deed|as_crispy_field }}
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-6">
                            {{ form.crest|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.division|as_crispy_field }}
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col">
                            {{ form.main_motivation|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            {{ form.lesser_motivations|as_crispy_field }}
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="row">
                        <div class="col-6">
                            {{ form.current_glory_points|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.total_glory_points|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            {{ form.current_experience_points|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.total_experience_points|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            {{ form.current_heroic_points|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.current_contact_points|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            {{ form.defence_no_od|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.defence_with_od|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            {{ form.reaction_no_od|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.reaction_with_od|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            {{ form.initiative_no_od|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.initiative_with_od|as_crispy_field }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="tab-pane fade" id="arcana" role="tabpanel" aria-labelledby="arcana-tab">
            <div class="row">
                <div class="col">
                    
                </div>
            </div>
        </div>
        
        <div class="tab-pane fade mt-2" id="stats" role="tabpanel" aria-labelledby="stats-tab">
            {% for aspect in aspects %}
                <div class="row">
                    <div class="col border">
                        <div id="div_id_aspect_{{aspect.id}}" class="form-group">
                            <label for="id_aspect_{{aspect.id}}" class="col-form-label font-weight-bold ">
                                {{ aspect.name }}
                            </label>
                            <div class="row">
                                {% with stringid=aspect.id|stringformat:'s' %}
                                    {% with key='character_aspect_'|add:stringid %}
                                        {{ form|get_item:key|as_crispy_field }}
                                    {% endwith %}
                                {% endwith %}
                            </div>
                        </div>
                    </div>
                    {% for characteristic in aspect.characteristics.all %}
                        <div class="col border">
                            <div id="div_id_characteristic_{{characteristic.id}}" class="form-group">
                                <label for="id_characteristic_{{characteristic.id}}" class="col-form-label font-italic">
                                    {{ characteristic.name }}
                                </label>
                                <div class="input-group">
                                    {% with stringid=characteristic.id|stringformat:'s' %}
                                        {% with key='character_characteristic_'|add:stringid|add:'_value' %}
                                            {{ form|get_item:key|as_crispy_field }}
                                        {% endwith %}
                                        {% with key='character_characteristic_'|add:stringid|add:'_od' %}
                                            {{ form|get_item:key|as_crispy_field }}
                                        {% endwith %}
                                        {% with key='character_characteristic_'|add:stringid|add:'_color' %}
                                            {{ form|get_item:key|as_crispy_field }}
                                        {% endwith %}
                                    {% endwith %}
                                    <!-- <input type="number" name="characteristic_{{characteristic.id}}" min="0" class="numberinput form-control" required="" id="id_characteristic_{{characteristic.id}}">
                                    <input type="number" min="0" max="{{ characteristic.max_level_overdrive }}" placeholder="OD" name="od_{{characteristic.id}}" min="0" class="numberinput form-control" required="" id="id_od_{{characteristic.id}}"> -->
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
        
        <div class="tab-pane fade" id="equipment" role="tabpanel" aria-labelledby="equipment-tab">
            <div class="row">
                <div class="col-4">
                    {{ form.armour|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.default_armour_nod|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.default_energy_nod|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.default_health_nod|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.default_grenade_stock|as_crispy_field }}
                </div>
            </div>
            
            <div class="row">
                <div class="col-2">
                    {{ form.final_total_health_points|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.final_total_hope_points|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.final_total_armour_points|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.final_total_energy_points|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.default_force_field|as_crispy_field }}
                </div>
            </div>
        </div>
        
        <div class="tab-pane fade" id="note" role="tabpanel" aria-labelledby="note-tab">
            <div class="row">
                <div class="col">
                    {{ form.notes|as_crispy_field }}
                </div>
            </div>
        </div>
        
        <div class="tab-pane fade" id="background" role="tabpanel" aria-labelledby="background-tab">
            <div class="row">
                <div class="col">
                    {{ form.background|as_crispy_field }}
                </div>
            </div>
        </div>
    </div>
    
    <button type="submit" class="btn btn-success">{% trans "Enregistrer" %}</button>
</form>
{% endblock %}

virtualtable/templates/virtualtable/character_value.html
{% load i18n %}
{% load static %}

<div class="{{ global_class }}" data-attr-code="{{ attr_code }}">
	{% spaceless %}
		<div class="d-block d-xl-none text-center">
			<div class="row m-0">
				<div class="col-4 p-0">
					<div>
						<button type="button" class="mr-0 align-top btn btn-link btn-sm manage-player" onclick="virtual_table.sub_value(this);">
							<i class="fas fa-minus-circle"></i>
						</button>
					</div>
				</div>
				<div class="col-4 p-0 max-width-when-compressed">
					<small class="badge badge-pill bg-{{ global_class }}" data-toggle="tooltip" title="{% trans full_label %}">{% trans label %}</small>
				</div>
				<div class="col-4 p-0">
					<div>
						<button type="button" class="btn m-0 align-top btn-link btn-sm manage-player" onclick="virtual_table.add_value(this);">
							<i class="fas fa-plus-circle"></i>
						</button>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<a href="#" data-toggle="modal" data-target="#updateValues" data-attr-code="{{ attr_code }}" class="badge badge-light badge-label" default-value="{% if default_value is None %}0{% else %}{{ default_value }}{% endif %}">{% if current_value is not None %}{{ current_value }}{% elif default_value is not None %}{{ default_value }}{% else %}0{% endif %}</a>
					<a class="m-0 ml-1 align-middle manage-player button-redo" href="#" onclick="virtual_table.reset_value(this,event);" role="button"><small><i class="fas fa-redo"></i></small></a>
				</div>
			</div>
		</div>
		<div class="d-xl-block d-none">
			<div class="row m-0 text-center justify-content-between">
				<div class="col-2 p-0">
					<div class="d-inline-block">
						<small class="badge badge-pill bg-{{ global_class }}" data-toggle="tooltip" title="{% trans full_label %}">{% trans label %}</small>
					</div>
				</div>
				<div class="col-2 p-0">
					<button type="button" class="mr-0 align-top btn btn-link btn-sm manage-player" onclick="virtual_table.sub_value(this);"><i class="fas fa-minus-circle"></i></button>
				</div>
				<div class="col-6 align-top stat-value">
					<div>
						<a href="#" data-toggle="modal" data-target="#updateValues" data-attr-code="{{ attr_code }}" class="badge badge-light badge-label" default-value="{% if default_value is None %}0{% else %}{{ default_value }}{% endif %}">{% if current_value is not None %}{{ current_value }}{% elif default_value is not None %}{{ default_value }}{% else %}0{% endif %}</a>
						<a class="m-0 ml-1 align-middle manage-player button-redo" href="#" onclick="virtual_table.reset_value(this,event);" role="button"><small><i class="fas fa-redo"></i></small></a>
					</div>
				</div>
				<div class="col-2 p-0">
					<button type="button" class="btn m-0 align-top btn-link btn-sm manage-player" onclick="virtual_table.add_value(this);"><i class="fas fa-plus-circle"></i></button>
				</div>
			</div>
		</div>
	{% endspaceless %}
</div>

virtualtable/templates/virtualtable/field.html
{% load crispy_forms_field %}

{% crispy_field field %}
{% include 'bootstrap4/layout/help_text_and_errors.html' %}

virtualtable/templates/virtualtable/test.html
{% extends 'virtualtable/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

virtualtable/templates/virtualtable/vt_faction_affinity.html
{% load i18n %}

{% for player in players %}
    <div class="form-group row">
        <label for="faction-affinity-{{ player.id }}" class="col-sm-12 col-form-label col-form-label-sm">{{ player.name }}</label>
        <div class="col-sm-11">
            <select id="faction-affinity-{{ player.id }}" class="form-control form-control-sm" pid="{{ player.id }}" onchange="virtual_table_cy.change_affinity(this);">
                <option value="-9">-9 ({% trans "Némésis, attaque à vue" %})</option>
                <option value="-8">-8</option>
                <option value="-7">-7</option>
                <option value="-6">-6</option>
                <option value="-5">-5 ({% trans "Animosité prononcée" %})</option>
                <option value="-4">-4</option>
                <option value="-3">-3</option>
                <option value="-2">-2</option>
                <option value="-1">-1 ({% trans "Rivalité, suspicion, méfiance" %})</option>
                <option value="0>" selected>0 ({% trans "Indifférence" %})</option>
                <option value="1">1 ({% trans "Intérêts communs" %})</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5 ({% trans "Bonne entente, partage d'informations" %})</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9 ({% trans "Confiance absolue" %})</option>
            </select>
        </div>
    </div>
{% endfor %}

virtualtable/templates/virtualtable/vt_list.html
{% extends "virtualtable/base.html" %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Liste des tables" %} - {% endblock %}

{% block content %}
<div class="row mt-3">
    <div class="col-12 mb-2">
        <a class="btn btn-primary float-right" href="{% url 'virtualtable:vt_help' %}" target="_blank" title="{% trans "Besoin d'aide ?" %}"><i class="fas fa-question-circle"></i> {% trans "Besoin d'aide ?" %}</a>
    </div>
    <div class="col-12">
        <table class="table table-sm table-striped table-bordered">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="text-center">{% trans "Invitation" %}</th>
                    <th scope="col" class="text-center">{% trans "Nom" %}</th>
                    <th scope="col" class="text-center">{% trans "Description" %}</th>
                    <th scope="col" class="text-center">{% trans "Personnages" %}</th>
                    <th scope="col" class="text-center">
                        {% trans "Actions" %}
                    </th>
                </tr>
            </thead>
            <tbody>
                {% if not virtualtable_list %}
                    <tr>
                        <td colspan="5" class="font-italic text-center">{% trans "Aucune table créée ni rejointe. Demandez à un MJ de vous fournir un lien d'invitation afin de pouvoir rejoindre une table" %}{% if user.game_master %}{% trans " ou créez en une directement" %}{% endif %}.</td>
                    </tr>
                {% endif %}
                {% for vt in virtualtable_list %}
                    <tr>
                        <td class="align-middle text-center vt-list-invit">
                            {% if not vt.token_has_expired %}
                                <div class="input-group">
                                    <input final-url="{% url 'virtualtable:join' vt.invitation_token %}" type="text" class="form-control" placeholder="{% trans 'Invitation' %}" aria-label="{% trans 'Invitation' %}" value="{{ vt.invitation_token }}">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="button" onclick="knightools.copy_invitation(this);">
                                            <i class="fas fa-copy"></i>
                                        </button>
                                    </div>
                                </div>
                            {% else %}
                                {% trans 'Fermée' %}
                            {% endif %}
                        </td>
                        <td class="align-middle text-center">{{ vt.name }}</td>
                        <td class="align-middle">{{ vt.description|safe_markdown }}</td>
                        <td class="align-middle">
                            {% if vt.players.all %}
                                <ul>
                                    {% for character in vt.players.all %}
                                        <li>{{ character.name }}</li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                {% trans "Aucun" %}
                            {% endif %}
                        </td>
                        <td class="align-middle text-center vt-list-manage">
                            <div class="btn-group btn-group" role="group" aria-label="Access Buttons">
                                <a href="{% url 'virtualtable:vt_detail' vt.id %}">
                                    <button type="button" role="button" class="btn btn-success" title="{% trans 'Voir' %}">
                                        <i class="fas fa-eye"></i>
                                    </button>
                                </a>
                                <a href="{% url 'virtualtable:vt_consent' vt.id %}">
                                    <button type="button" role="button" class="btn btn-info" title="{% trans 'Consentement' %}">
                                        <i class="fas fa-list-check"></i>
                                    </button>
                                </a>
                            </div>
                            {% if vt.owned_by_user %}
                                <hr>
                                <div class="btn-group btn-group" role="group" aria-label=" ManagementButtons">
                                    <a href="{% url 'virtualtable:vt_update' vt.id %}">
                                        <button type="button" role="button" class="btn btn-secondary" title="{% trans 'Gérer' %}">
                                            <i class="fas fa-cog"></i>
                                        </button>
                                    </a>
                                    <a href="{% url 'virtualtable:vt_delete' vt.id %}">
                                        <button type="button" role="button" class="btn btn-danger" title="{% trans 'Supprimer' %}">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </a>
                                </div>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            {% if user.game_master %}
            <tfoot>
                <tr>
                    <td colspan="5">
                        <a href="{% url 'virtualtable:vt_create' %}" class="btn btn-success"><i class="fas fa-plus"></i> {% trans "Créer" %}</a>
                    </td>
                </tr>
            </tfoot>
            {% endif %}
        </table>
    </div>
</div>

{% endblock %}