gm/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import misc, calculators, searches, lists, details, prints, faq

app_name = 'gm'
urlpatterns = [
    path('', misc.IndexView.as_view(), name='index'),
    path('about/', misc.AboutView.as_view(), name='about'),
    path('ai_generator/', cache_page(0)(misc.generateAI), name='ai_generator'),
    path('ai_generator/<codename>/', misc.generateAI, name='ai_informations'),
    path('ajax/autocomplete.json', misc.AutocompleteView.as_view(), name='autocomplete'),
    path('ajax/theme', misc.SetTheme.as_view(), name='set_theme'),
    
    path('weapon/', lists.WeaponListView.as_view(), name='weapon_list'),
    path('module/', lists.ModuleListView.as_view(), name='module_list'),
    path('effect/', lists.EffectListView.as_view(), name='effect_list'),
    path('overdrive/', lists.OverdriveListView.as_view(), name='overdrive_list'),
    path('enhancement/', lists.EnhancementListView.as_view(), name='enhancement_list'),
    path('armour/', lists.ArmourListView.as_view(), name='armour_list'),
    path('division/', lists.DivisionListView.as_view(), name='division_list'),
    path('arcana/', lists.ArcanaListView.as_view(), name='arcana_list'),
    path('crest/', lists.CrestListView.as_view(), name='crest_list'),
    path('archetype/', lists.ArchetypeListView.as_view(), name='archetype_list'),
    path('great_deed/', lists.GreatDeedListView.as_view(), name='great_deed_list'),
    path('heroic-ability/', lists.HeroicAbilityListView.as_view(), name='heroic_ability_list'),
    path('vehicle/', lists.VehicleListView.as_view(), name='vehicle_list'),
    path('style/', lists.StyleListView.as_view(), name='style_list'),
    path('trauma/', lists.TraumaListView.as_view(), name='trauma_list'),
    path('mecha/', lists.MechaArmourListView.as_view(), name='mecha_list'),
    path('npc-ability/', lists.NonPlayerCharacterAbilityListView.as_view(), name='npc_ability_list'),
    path('twin_ability/', lists.ArmourTwinAbilityListView.as_view(), name='twin_list'),
    path('ultimate_aptitude/', lists.UltimateAptitudeListView.as_view(), name='ultimate_list'),
    
    path('weapon/<int:pk>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<int:pk>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<int:pk>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<int:pk>/', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<int:pk>/', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/<int:pk>/', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<int:pk>/', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<int:pk>/', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<int:pk>/', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('heroic-ability/<int:pk>/', details.HeroicAbilityDetailView.as_view(), name='heroic_ability_detail'),
    path('vehicle/<int:pk>/', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('trauma/<int:pk>/', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('ultimate_aptitude/<int:pk>/', details.UltimateAptitudeDetailView.as_view(), name='ultimate_detail'),
    
    path('weapon/<slug:slug>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<slug:slug>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<slug:slug>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<slug:slug>/', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<slug:slug>/', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/classified', details.ArmourClassifiedView.as_view(), name='armour_unknown'),
    path('armour/<slug:slug>/', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<slug:slug>/', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<slug:slug>/', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<slug:slug>/', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('heroic-ability/<slug:slug>/', details.HeroicAbilityDetailView.as_view(), name='heroic_ability_detail'),
    path('archetype/<slug:slug>/', details.ArchetypeDetailView.as_view(), name='archetype_detail'),
    path('crest/<slug:slug>/', details.CrestDetailView.as_view(), name='crest_detail'),
    path('vehicle/<slug:slug>/', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('style/<slug:slug>/', details.StyleDetailView.as_view(), name='style_detail'),
    path('trauma/<slug:slug>/', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('mecha/classified', details.MechaArmourClassifiedView.as_view(), name='mecha_unknown'),
    path('mecha/<slug:slug>/', details.MechaArmourDetailView.as_view(), name='mecha_detail'),
    path('npc-ability/<slug:slug>/', details.NonPlayerCharacterAbilityDetailView.as_view(), name='npc_ability_detail'),
    path('ultimate_aptitude/<slug:slug>/', details.UltimateAptitudeDetailView.as_view(), name='ultimate_detail'),
    
    path('longbow_calculator/', calculators.LongbowCalculatorView.as_view(), name='longbow_calculator'),
    path('weapon-calculator/', calculators.WeaponCalculatorView.as_view(), name='weapon_calculator'),
    
    path('faq/v1/', faq.QuestionV1ListView.as_view(), name='faqv1'),
    path('faq/v1.5/', faq.QuestionV1Dot5ListView.as_view(), name='faqv1.5'),
    
    path('search/', searches.search, name='search'),
    
    path('print/weapon/', prints.WeaponPrintListView.as_view(), name='print_weapon'),
    path('print/module/', prints.ModulePrintListView.as_view(), name='print_module'),
    path('print/overdrive/', prints.OverdrivePrintListView.as_view(), name='print_overdrive'),
    path('print/enhancement/', prints.EnhancementPrintListView.as_view(), name='print_enhancement'),
    path('print/trauma/', prints.TraumaPrintListView.as_view(), name='print_trauma'),
    
    # Retrocomp
    path('skill/', lists.HeroicSkillListRedirectView.as_view(), name='skill_list'),
    path('skill/<int:pk>/', details.HeroicSkillDetailRedirectView.as_view(), name='skill_detail'),
    path('skill/<slug:slug>/', details.HeroicSkillDetailRedirectView.as_view(), name='skill_detail'),
    path('stance/', lists.StanceListRedirectView.as_view(), name='stance_list'),
    path('stance/<slug:slug>/', details.StanceDetailRedirectView.as_view(), name='stance_detail'),
    path('npc_capacity/', lists.NonPlayerCharacterCapacityListRedirectView.as_view(), name='npc_capacity_list'),
    path('npc_capacity/<slug:slug>/', details.NonPlayerCharacterCapacityDetailRedirectView.as_view(), name='npc_capacity_detail'),
    
]

knight_master_overview/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static

from .views import account, martor

urlpatterns = [
    path('camelot/', admin.site.urls),
    path('martor/uploader/', martor.markdown_uploader, name="markdown_uploader_page"),
    path('martor/', include('martor.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('api/', include('api.urls')),
    path('accounts/login/', account.JointLoginSignupView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
]

gm_urls = ([
    path('', include('gm.urls')),
], 'gm')


virtualtable_urls = ([
    path('', include('virtualtable.urls')),
], 'virtualtable')

urlpatterns += i18n_patterns(
    path('', include('gm.urls')),
    path('virtualtable/', include('virtualtable.urls')),
    path('api/', include('api.urls')),
    path('users/', include('users.urls')),
    prefix_default_language=True
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gm/views/calculators.py
from django.shortcuts import render
from django.views import generic
from django.utils.translation import get_language
from django.db.models import Prefetch

from ..models.weaponry import (
    Weapon, WeaponI18n, ReachI18n, WeaponAttackI18n,
    WeaponAttackEffectI18n
)

class LongbowCalculatorView(generic.View):
    def get(self, request):
        return render(request, 'gm/calculators/longbow.html', {
            "longbow": Weapon.objects.get(slug='fusil-longbow'),
        })

class WeaponCalculatorView(generic.View):
    def get(self, request):
        language = get_language()
        weapons = (
            WeaponI18n
            .objects
            .filter(
                translations__language_code=language,
                calculator=True
            )
            .prefetch_related(
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.filter(
                        calculator_behaviour='INI',
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='initial_attacks'
                ),
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.filter(
                        calculator_behaviour='LST',
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='listing_attacks'
                ),
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.filter(
                        calculator_behaviour='REP',
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='replacement_attacks'
                ),
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.filter(
                        calculator_behaviour='REM',
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='removal_attacks'
                ),
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.filter(
                        calculator_behaviour='RED',
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='reduction_attacks'
                ),
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.exclude(
                        calculator_behaviour='INI'
                    ).filter(
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='non_initial_attacks'
                ),
            )
            .all()
        )
        reaches = ReachI18n.objects.filter(translations__language_code=language).all()
        
        return render(request, 'gm/calculators/weapon.html', {
            "weapons": weapons,
            "reaches": reaches
        })
    

gm/views/faq.py
from django.views import generic
from django.db.models import Q, Count, Prefetch
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.faq import Category, Question, CategoryTreebeardI18n, QuestionI18n

class QuestionV1ListView(generic.ListView):
    template_name = 'gm/faq/list.html'
    context_object_name = 'faq'
    
    def get_context_data(self, **kwargs):
        context = super(QuestionV1ListView, self).get_context_data(**kwargs)
        
        prefetch = Prefetch(
            'questions',
            queryset=Question.objects.filter(v1=True, gm=False).order_by('-created')
        )
        
        if self.request.user.is_authenticated and self.request.user.game_master:
            prefetch = Prefetch(
                'questions',
                queryset=Question.objects.filter(v1=True).order_by('-created')
            )
        
        categories = Category.objects.prefetch_related(prefetch).all()
        displayed_category = []
        index_category = {}
        
        for category in categories:
            index_category[category.id] = len(displayed_category)
            displayed_category.append((category, category.is_leaf_node() and len(category.questions.all()) > 0))
            
            if category.is_leaf_node():
                if len(category.questions.all()) > 0:
                    for ancestor in category.get_ancestors():
                        displayed_category[index_category[ancestor.id]] = (ancestor, True)
        
        context['displayed_categories'] = displayed_category
        
        return context
        
    def get_queryset(self):
        """Return list of weapon."""
        return (Question
            .objects
            .filter(
                v1=True
            )
            .order_by('category', '-created'))

class QuestionV1Dot5ListView(generic.ListView):
    template_name = 'gm/faq/list.html'
    context_object_name = 'faq'
    
    def get_context_data(self, **kwargs):
        context = super(QuestionV1Dot5ListView, self).get_context_data(**kwargs)
        
        prefetch = Prefetch(
            'questions',
            queryset=QuestionI18n.objects.filter(v1_5=True, gm=False).order_by('-created')
        )
        
        if self.request.user.is_authenticated and self.request.user.game_master:
            prefetch = Prefetch(
                'questions',
                queryset=QuestionI18n.objects.filter(v1_5=True).order_by('-created')
            )
        
        categories = CategoryTreebeardI18n.objects.prefetch_related(prefetch).all()
        displayed_category = []
        index_category = {}
        
        for category in categories:
            index_category[category.id] = len(displayed_category)
            displayed_category.append((category, category.is_leaf() and len(category.questions.all()) > 0))
            
            if category.is_leaf():
                if len(category.questions.all()) > 0:
                    for ancestor in category.get_ancestors():
                        displayed_category[index_category[ancestor.id]] = (ancestor, True)
        
        context['displayed_categories'] = displayed_category
        
        return context
        
    def get_queryset(self):
        """Return list of weapon."""
        return (QuestionI18n
            .objects
            .filter(
                v1_5=True
            )
            .order_by('category__translations__name', '-created'))

gm/templates/gm/lists/module.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Liste des modules" %} - {% endblock %}

{% block display_printer %}d-sm-block{% endblock display_printer %}
{% block printer %}{% url 'gm:print_module' %}{% endblock printer %}

{% block content %}
    <div class="mt-3">
        <h1 class="text-center font-weight-bold">{% trans "Liste des modules" %}</h1>
        <div class="card mb-3">
            <div class="card-header position-relative">
                <a class="text-decoration-none stretched-link" data-toggle="collapse" href="#collapsePresentation" aria-expanded="false" aria-controls="collapsePresentation">
                    <h6 class="font-weight-bold font-italic mb-0">
                        {% trans "Introduction" %}
                        <i class="fa fa-plus-square"></i>
                    </h6>
                </a>
            </div>
            <div id="collapsePresentation" class="collapse" aria-labelledby="presentation">
                <div class="card-body">
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                            Chaque méta-armure est unique et possède quantité de personnalisations. Même si les divers châssis constituent des bases solides et inaltérables, notamment en termes de capacité spéciale, chaque chevalier aime ajouter à sa méta-armure des équipements que l'on nomme généralement « modules ». Ces modules s'ajoutent à l'armure nue et remplissent peu à peu les espaces disponibles, espaces nommés « slots ». Ces slots sont limités et sont présents sur les jambes, les bras, le tronc et la tête de la méta-armure. Chaque modèle possède un nombre de slots différent.
                        {% endblocktrans %}
                    </p>
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                            Il est à noter que les modules ne sont jamais totalement détaillés. En effet, sur la plupart des modules est présente une liste d'équipements possibles représentant l'effet du module. C'est au joueur de choisir l'équipement correspondant. Ce choix n'a qu'une valeur cosmétique, mais sert à la personnalisation de la méta-armure. Les modules sont intimement liés à l'armure. Ils ne peuvent donc être utilisés que lorsque l'armure est complètement déployée.
                        {% endblocktrans %}
                    </p>
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                            Certains modules peuvent être augmentés et possèdent des niveaux, généralement de 1 à 3. Pour se doter du niveau 2 ou 3 d'un module, il faut posséder les précédents. Ces niveaux ont un coût indiqué dans le descriptif du module.
                        {% endblocktrans %}
                    </p>
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                            En termes de description, les modules possèdent un score de slots associé à un terme représentant le ou les slots qu'ils occupent et leur emplacement.
                        {% endblocktrans %}
                    </p>
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                            Autrement, chaque module a un coût en points de gloire indiqué dans son descriptif. Les autres effets sont, eux aussi, détaillés dans le descriptif.
                        {% endblocktrans %}
                    </p>
                    <p class="text-justify">
                        {% url "gm:overdrive_list" as url_od %}
                        {% blocktrans trimmed with url_od=url_od %}
                            Chaque module est organisé dans différentes catégories : modules de déplacement, modules de combat, modules tactiques, modules utilitaires, améliorations et armes automatisées. Les <a href="{{ url_od }}">modules d'overdrive</a> font l'objet d'une section spécifique sur le site.
                        {% endblocktrans %}
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-3">
        {% include 'gm/misc/filter_datatable.html' with categories=categories sources=sources rarities=rarities activations=activations user=user only %}
        <table data-order='[[ 1, "asc" ], [ 2, "asc" ], [ 0, "asc" ]]' class="table table-sm table-hover dt-enable">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="w-25">{% trans "Nom" %}</th>
                    <th scope="col" class="category w-25">
                        <div class="d-none d-sm-block">{% trans "Catégorie" %}</div>
                        <div class="d-block d-sm-none">{% trans "Catég." %}</div>
                    </th>
                    <th scope="col" class="w-25 rarity">{% trans "Rareté" %}</th>
                    <th scope="col" class="w-25">{% trans "Prix" %}</th>
                    <th scope="col" class="source" data-visible="false">{% trans "Source" %}</th>
                    <th scope="col" class="activation" data-visible="false">{% trans "Activation" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for module in module_list %}
                    {% with first_level=module.levels.all|first %}
                        {% for level in module.levels.all %}
                            <tr>
                                <td data-order="{{ module.name|slugify }}" class="position-relative">
                                    <a class="stretched-link" href="{% url 'gm:module_detail' module.slug %}">{{ module.name }}{% if module.levels.all|length > 1 %} {% trans "niv." %} {{ level.level }}{% endif %}</a>
                                </td>
                                <td data-search="{{ module.category.name }}">
                                    <div class="d-none d-sm-block">{{ module.category.name }}</div>
                                    <div class="d-block d-sm-none">{{ module.category.short_name }}</div>
                                </td>
                                <td data-order="{{ level.rarity.id }}">
                                    <span class="thumbnail-bg bg-custom-rarity-{{ level.rarity.id }}"></span>
                                    <span class="d-none d-sm-inline">{{ level.rarity.name }}</span>
                                    <span class="d-inline d-sm-none">{{ level.rarity.name|truncatechars:3 }}</span>
                                </td>
                                <td data-order="{{ level.cost }}">{{ level.cost }} PG</td>
                                <td>{{ module.source.name }}</td>
                                <td>{{ level.activation.name }}</td>
                            </tr>
                        {% endfor %}
                    {% endwith%}
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    <link rel="stylesheet" type="text/css" href="{% static 'gm/dt/datatables.min.css' %}"/>
    {% with locale_dt='gm/dt/locale.'|add:LANGUAGE_CODE|add:'.js' %}
        <script type="text/javascript" src="{% static locale_dt %}"></script>
    {% endwith %}
    <script type="text/javascript" src="{% static 'gm/dt/datatables.min.js' %}"></script>
{% endblock %}

gm/templates/gm/lists/overdrive.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Liste des overdrives" %} - {% endblock %}

{% block display_printer %}d-sm-block{% endblock display_printer %}
{% block printer %}{% url 'gm:print_overdrive' %}{% endblock printer %}

{% block content %}
    {% regroup overdrive_list by characteristic.aspect as overdrives_by_aspect %}
    <div class="mt-3">
        <h1 class="text-center font-weight-bold">{% trans "Liste des overdrives" %}</h1>
        <div class="card mb-3">
            <div class="card-header position-relative">
                <a class="text-decoration-none stretched-link" data-toggle="collapse" href="#collapsePresentation" aria-expanded="false" aria-controls="collapsePresentation">
                    <h6 class="font-weight-bold font-italic mb-0">
                        {% trans "Introduction" %}
                        <i class="fa fa-plus-square"></i>
                    </h6>
                </a>
            </div>
            <div id="collapsePresentation" class="collapse" aria-labelledby="presentation">
                <div class="card-body">
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                        Les modules d'overdrive offrent des overdrives aux caractéristiques, c'est-à-dire un bonus de 1 réussite automatique par overdrive, sur chaque combo les impliquant.
                        {% endblocktrans %}
                    </p>
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                        Ils s'étendent tous sur 5 niveaux (mais peuvent atteindre des niveaux supérieurs avec certains modules, comme le mode type de la méta-armure Warrior). Peu importe leur nombre, ils ne prennent jamais d'emplacement. Généralement, ils sont inclus à l'intérieur de la méta-armure et n'ont pas besoin d'être décrits.
                        {% endblocktrans %}
                    </p>
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                        Comme pour les autres modules, il faut acheter les niveaux précédents pour obtenir les niveaux 2, 3, 4 et 5.
                        {% endblocktrans %}
                    </p>
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                        Si l'armure du chevalier possède déjà des overdrives que vous voulez augmenter, ceux-ci comptent dans le coût d'achat. Par exemple, si l'armure d'un personnage possède 1 overdrive de base en <em>Tir</em>, le personnage devra payer 30 PG pour le passer au deuxième et ainsi de suite.
                        {% endblocktrans %}
                    </p>
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                        Il est à noter qu'au-delà de deux niveaux d'overdrive, ceux achetés comptent comme des modules rares. Il faut donc que l'accès aux modules rares soit débloqué par le MJ avant de pouvoir les acquérir.
                        {% endblocktrans %}
                    </p>
                    <p class="text-justify">
                        {% blocktrans trimmed %}
                        Enfin, en plus des réussites automatiques, chaque type d'overdrive amène parfois un lot de bonus par niveau, permettant aux PJ d'être plus héroïques encore. Ils sont à inscrire dans la liste des capacités du personnage. Certains sont simplement narratifs, c'est-à-dire qu'ils permettent aux PJ d'agrémenter la description d'une action et d'autres modifient ou ajoutent des points de règles. Il est à noter qu'ils ne fonctionnent que lorsque le personnage est en méta-armure. Jamais sans.
                        {% endblocktrans %}
                    </p>
                </div>
            </div>
        </div>
        
        <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
            {% for aspect, overdrives in overdrives_by_aspect %}
                {% with slug_aspect=aspect.name|slugify %}
                <li class="nav-item">
                    <a class="nav-link px-1" id="{{ slug_aspect }}-tab" data-toggle="tab" href="#{{ slug_aspect }}" role="tab" aria-controls="{{ slug_aspect }}" aria-selected="false">{{ aspect.name }}</a>
                </li>
                {% endwith %}
            {% endfor %}
        </ul>
    </div>
    <div class="mt-3">
        <div class="tab-content" id="myTabContent">
            {% for aspect, overdrives in overdrives_by_aspect %}
                {% with slug_aspect=aspect.name|slugify %}
                    <div class="tab-pane fade show" id="{{ slug_aspect }}" role="tabpanel" aria-labelledby="{{ slug_aspect }}-tab">
                        {% regroup overdrives by characteristic as overdrives_by_characteristics %}
                        {% for characteristic, final_overdrives in overdrives_by_characteristics %}
                            {% with slug_characteristic=characteristic.name|slugify %}
                                <div class="card my-3">
                                    <div class="card-header position-relative">
                                        <a class="text-decoration-none stretched-link" data-toggle="collapse" href="#collapse{{ slug_characteristic }}" aria-expanded="false" aria-controls="collapse{{ slug_characteristic }}">
                                            <h5 class="font-weight-bold font-italic mb-0 text-center">
                                                {{ characteristic.name }}
                                                <i class="fa fa-plus-square"></i>
                                            </h5>
                                        </a>
                                    </div>
                                    <div id="collapse{{ slug_characteristic }}" class="collapse" aria-labelledby="{{ slug_characteristic }}">
                                        <div class="card-body">
                                            <div>{{ characteristic.overdrive_global_description }}</div>
                                            <div>
                                                {% for overdrive in final_overdrives %}
                                                    <div class="card my-3">
                                                        <div class="card-header bg-custom-rarity-header-{{ overdrive.rarity.id }} position-relative">
                                                            <a class="stretched-link" href="{% url 'gm:overdrive_detail' overdrive.slug %}">
                                                                <h5 class="font-weight-bold font-italic mb-0">
                                                                    {% trans "Niv." %} {{ overdrive.level }} : {{ overdrive.cost }}  {% trans "PG" %}
                                                                </h5>
                                                            </a>
                                                        </div>
                                                        {% if overdrive.description %}
                                                        <div class="card-body">
                                                            <div class="text-justify markdown-format">{{ overdrive.description|safe_markdown }}</div>
                                                        </div>
                                                        {% endif %}
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endwith %}
                        {% endfor %}
                    </div>
                {% endwith %}
            {% endfor %}
        </div>
    </div>
{% endblock %}