gm/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import misc, calculators, searches, lists, details, prints, faq

app_name = 'gm'
urlpatterns = [
    path('', misc.IndexView.as_view(), name='index'),
    path('about/', misc.AboutView.as_view(), name='about'),
    path('ai_generator/', cache_page(0)(misc.generateAI), name='ai_generator'),
    path('ai_generator/<codename>/', misc.generateAI, name='ai_informations'),
    path('ajax/autocomplete.json', misc.AutocompleteView.as_view(), name='autocomplete'),
    path('ajax/theme', misc.SetTheme.as_view(), name='set_theme'),
    
    path('weapon/', lists.WeaponListView.as_view(), name='weapon_list'),
    path('module/', lists.ModuleListView.as_view(), name='module_list'),
    path('effect/', lists.EffectListView.as_view(), name='effect_list'),
    path('overdrive/', lists.OverdriveListView.as_view(), name='overdrive_list'),
    path('enhancement/', lists.EnhancementListView.as_view(), name='enhancement_list'),
    path('armour/', lists.ArmourListView.as_view(), name='armour_list'),
    path('division/', lists.DivisionListView.as_view(), name='division_list'),
    path('arcana/', lists.ArcanaListView.as_view(), name='arcana_list'),
    path('crest/', lists.CrestListView.as_view(), name='crest_list'),
    path('archetype/', lists.ArchetypeListView.as_view(), name='archetype_list'),
    path('great_deed/', lists.GreatDeedListView.as_view(), name='great_deed_list'),
    path('heroic-ability/', lists.HeroicAbilityListView.as_view(), name='heroic_ability_list'),
    path('vehicle/', lists.VehicleListView.as_view(), name='vehicle_list'),
    path('style/', lists.StyleListView.as_view(), name='style_list'),
    path('trauma/', lists.TraumaListView.as_view(), name='trauma_list'),
    path('mecha/', lists.MechaArmourListView.as_view(), name='mecha_list'),
    path('npc-ability/', lists.NonPlayerCharacterAbilityListView.as_view(), name='npc_ability_list'),
    path('twin_ability/', lists.ArmourTwinAbilityListView.as_view(), name='twin_list'),
    path('ultimate_aptitude/', lists.UltimateAptitudeListView.as_view(), name='ultimate_list'),
    
    path('weapon/<int:pk>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<int:pk>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<int:pk>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<int:pk>/', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<int:pk>/', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/<int:pk>/', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<int:pk>/', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<int:pk>/', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<int:pk>/', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('heroic-ability/<int:pk>/', details.HeroicAbilityDetailView.as_view(), name='heroic_ability_detail'),
    path('vehicle/<int:pk>/', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('trauma/<int:pk>/', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('ultimate_aptitude/<int:pk>/', details.UltimateAptitudeDetailView.as_view(), name='ultimate_detail'),
    
    path('weapon/<slug:slug>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<slug:slug>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<slug:slug>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<slug:slug>/', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<slug:slug>/', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/classified', details.ArmourClassifiedView.as_view(), name='armour_unknown'),
    path('armour/<slug:slug>/', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<slug:slug>/', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<slug:slug>/', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<slug:slug>/', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('heroic-ability/<slug:slug>/', details.HeroicAbilityDetailView.as_view(), name='heroic_ability_detail'),
    path('archetype/<slug:slug>/', details.ArchetypeDetailView.as_view(), name='archetype_detail'),
    path('crest/<slug:slug>/', details.CrestDetailView.as_view(), name='crest_detail'),
    path('vehicle/<slug:slug>/', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('style/<slug:slug>/', details.StyleDetailView.as_view(), name='style_detail'),
    path('trauma/<slug:slug>/', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('mecha/classified', details.MechaArmourClassifiedView.as_view(), name='mecha_unknown'),
    path('mecha/<slug:slug>/', details.MechaArmourDetailView.as_view(), name='mecha_detail'),
    path('npc-ability/<slug:slug>/', details.NonPlayerCharacterAbilityDetailView.as_view(), name='npc_ability_detail'),
    path('ultimate_aptitude/<slug:slug>/', details.UltimateAptitudeDetailView.as_view(), name='ultimate_detail'),
    
    path('longbow_calculator/', calculators.LongbowCalculatorView.as_view(), name='longbow_calculator'),
    path('weapon-calculator/', calculators.WeaponCalculatorView.as_view(), name='weapon_calculator'),
    
    path('faq/v1/', faq.QuestionV1ListView.as_view(), name='faqv1'),
    path('faq/v1.5/', faq.QuestionV1Dot5ListView.as_view(), name='faqv1.5'),
    
    path('search/', searches.search, name='search'),
    
    path('print/weapon/', prints.WeaponPrintListView.as_view(), name='print_weapon'),
    path('print/module/', prints.ModulePrintListView.as_view(), name='print_module'),
    path('print/overdrive/', prints.OverdrivePrintListView.as_view(), name='print_overdrive'),
    path('print/enhancement/', prints.EnhancementPrintListView.as_view(), name='print_enhancement'),
    path('print/trauma/', prints.TraumaPrintListView.as_view(), name='print_trauma'),
    
    # Retrocomp
    path('skill/', lists.HeroicSkillListRedirectView.as_view(), name='skill_list'),
    path('skill/<int:pk>/', details.HeroicSkillDetailRedirectView.as_view(), name='skill_detail'),
    path('skill/<slug:slug>/', details.HeroicSkillDetailRedirectView.as_view(), name='skill_detail'),
    path('stance/', lists.StanceListRedirectView.as_view(), name='stance_list'),
    path('stance/<slug:slug>/', details.StanceDetailRedirectView.as_view(), name='stance_detail'),
    path('npc_capacity/', lists.NonPlayerCharacterCapacityListRedirectView.as_view(), name='npc_capacity_list'),
    path('npc_capacity/<slug:slug>/', details.NonPlayerCharacterCapacityDetailRedirectView.as_view(), name='npc_capacity_detail'),
    
]

knight_master_overview/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static

from .views import account, martor

urlpatterns = [
    path('camelot/', admin.site.urls),
    path('martor/uploader/', martor.markdown_uploader, name="markdown_uploader_page"),
    path('martor/', include('martor.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('api/', include('api.urls')),
    path('accounts/login/', account.JointLoginSignupView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
]

gm_urls = ([
    path('', include('gm.urls')),
], 'gm')


virtualtable_urls = ([
    path('', include('virtualtable.urls')),
], 'virtualtable')

urlpatterns += i18n_patterns(
    path('', include('gm.urls')),
    path('virtualtable/', include('virtualtable.urls')),
    path('api/', include('api.urls')),
    path('users/', include('users.urls')),
    prefix_default_language=True
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import include, path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'users'
urlpatterns = [
    path('favorites/', cache_page(0)(views.ListFavoritesView.as_view()), name='fav_list'),
    
    # Profile part
    path('profile/', cache_page(0)(views.ProfileView.as_view()), name='profile'),
    path('del_user/', cache_page(0)(views.DeleteUserView.as_view()), name='del_user'),
    path('password/', cache_page(0)(views.PasswordChangeView.as_view()), name='change_password'),
    
    
    # Fav from detail part
    path('fav_add/', cache_page(0)(views.AddToFavView.as_view()), name='fav_add'),
    path('fav_del/', cache_page(0)(views.DelFromFavView.as_view()), name='fav_del'),
    
    # Item management part
    path('fav_copy_item/', cache_page(0)(views.MoveFavItemView.as_view()), name='fav_copy_item'),
    path('fav_del_item/', cache_page(0)(views.DelFavItemView.as_view()), name='fav_del_item'),
    path('fav_edit_item/', cache_page(0)(views.EditItemToFavView.as_view()), name='fav_edit_item'),
    path('fav_move_item/', cache_page(0)(views.MoveFavItemView.as_view()), name='fav_move_item'),
    
    # List management part
    path('fav_add_list/', cache_page(0)(views.AddFavListView.as_view()), name='fav_add_list'),
    path('fav_del_list/', cache_page(0)(views.DelFavListView.as_view()), name='fav_del_list'),
    path('fav_edit_list/', cache_page(0)(views.EditFavListView.as_view()), name='fav_edit_list'),
    path('fav_order_list/', cache_page(0)(views.OrderFavListView.as_view()), name='fav_order_list'),
]

users/forms.py
from django.utils.translation import gettext_lazy

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from allauth.account.forms import SignupForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

class CustomUserProfileForm(UserChangeForm):
    game_master_question = forms.CharField(required=False, label="question", help_text=gettext_lazy("Ne pas mettre d'article défini devant la réponse (le, la, l', les...) ! Évitez les accents si possibles. Exemple : «La Désolation» donnerait : «Desolation» ; «L'Éphémère» deviendrait «ephemere»."))
    activation_code = forms.CharField(max_length=1024, label=gettext_lazy("Code d'activation"), widget=forms.Textarea, required=False, help_text=gettext_lazy('Un code par ligne si vous souhaitez en saisir plusieurs.'))
    first_name = forms.CharField(max_length=30, required=False, label=gettext_lazy("Pseudo (public)"))
    
    def __init__(self, *args, **kwargs):
        super(CustomUserProfileForm, self).__init__(*args, **kwargs)
        
        if self.instance.get_next_game_master_question():
            remaining_tries = 5 - self.instance.asked_game_master_questions.count()
            self.fields["game_master_question"].label = gettext_lazy('%s (Essais restants : %d)' % (self.instance.get_next_game_master_question().question, remaining_tries))
    
    class Meta:
        model = CustomUser
        fields = ('last_name', 'first_name', 'username', 'email', 'game_master', 'gest_account', 'prechecked_sources')

class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, required=False, label=gettext_lazy("Pseudo (public)"))
    
    def save(self, request):

        # Ensure you call the parent class's save.
        # .save() returns a User object.
        user = super(CustomSignupForm, self).save(request)

        # Add your own processing here.
        # user.game_master = self.cleaned_data['game_master']
        user.first_name = self.cleaned_data['first_name']
        user.save()
        
        # You must return the original result.
        return user
    
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields
    

users/templates/users/base.html
{% extends 'gm/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'users/css/style.css' %}" />
{% endblock %}

users/templates/users/change_password.html
{% extends 'users/base.html' %}

{% load static %}
{% load martortags %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load gm_extras %}

{% block title %}{% trans "Modif. mot de passe" %} - {% endblock %}

{% block content %}
<form method="post">
    <h1 class="text-center">{% trans "Modification de votre mot de passe" %}</h1>
	{% csrf_token %}
    <div class="row">
        <div class="col">
            {{ form.old_password|as_crispy_field }}
        </div>
        <div class="col">
            {{ form.new_password1|as_crispy_field }}
		</div>
		<div class="col-12"></div>
		<div class="col"></div>
        <div class="col">
            {{ form.new_password2|as_crispy_field }}
        </div>
    </div>
    <button type="submit" class="btn btn-success">{% trans "Enregistrer" %}</button>
</form>
{% endblock %}

users/templates/users/delete_account.html
{% extends 'users/base.html' %}

{% load static %}
{% load martortags %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load gm_extras %}

{% block title %}{% trans "Profil" %} - {% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'users/js/profile.js' %}"></script>
{% endblock js %}

{% block content %}
    <h1 class="text-center text-danger">{% trans "Suppression de compte" %}</h1>
    <form method="post">{% csrf_token %}
        <div class="">
            <p>{% blocktrans trimmed %}Vous vous apprêtez à supprimer votre compte de {{ KNIGHTOOLS_SITE_NAME }}. Cette suppression est définitive ! Vos favoris, vos tables virtuelles, vos personnages sur les tables virtuelles que vous avez rejoint, toutes ces données seront supprimées sans possibilité de les récupérer.{% endblocktrans %}</p>
            <p>{% blocktrans trimmed %}Vous pourrez toujours recréer un compte plus tard, ou même continuer à naviguer sur le site de façon anonyme.{% endblocktrans %}</p>
            <p>{% blocktrans trimmed %}Confirmez-vous la suppression ?{% endblocktrans %}</p>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete-account-confirm">{% trans "Supprimer votre compte" %}</button>
        </div>
        
        
        <div class="modal fade" id="delete-account-confirm" tabindex="-1" role="dialog" aria-labelledby="delete-account-confirm-title" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header bg-danger">
                        <h5 class="modal-title" id="delete-account-confirm-title">{% trans "Sûr hein ? Pas de regrets ?" %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                    <p>
                        {% blocktrans %}Vous confirmez vraiment que vous souhaitez laisser la planète à la merci de l'Anathème ? Vous ne souhaitez plus secourir d'innocents ? Combattre des monstres ? Être héroïque ?{% endblocktrans %}
                    </p>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-danger" value="{% trans 'Oui, je veux oublier.' %}">
                        <button type="button" class="btn btn-secondary btn-knightools-cancel" data-dismiss="modal">{% trans 'Non, je suis le danger.' %}</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    
{% endblock %}

users/templates/users/fav_list.html
{% extends 'users/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Favoris" %} - {% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'users/js/favorites.js' %}"></script>
{% endblock js %}

{% block content %}
    <div class="row mt-3 sortable">
        {% for fav_list in favorite_lists %}
            {% if fav_list.id == 0 %}
                <div class="col-12"></div>
            {% endif %}
            {% include 'users/fav_list_content.html' with fav_list=fav_list only %}
        {% endfor %}
        <div class="col-12 col-md-6 mb-3">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">{{ fav_list.name }}</h3>
                </div>
                <div class="card-body text-center">
                    <a href="#" class="btn btn-outline-success w-100 py-3 fav-list-add"><i class="fas fa-plus-circle"></i></a>
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal fade" id="edit-item" tabindex="-1" role="dialog" aria-labelledby="edit-item-label" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="edit-item-label">{% trans "Modifier un favori" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="edit-item-form" onsubmit="favorites.save_item(); return false;">
                        <input type="hidden" id="fav-item-type" />
                        <input type="hidden" id="fav-item-id" />
                        <div class="form-group">
                            <label for="fav-item-note" class="col-form-label">{% trans "Descriptif (optionnel) :" %}</label>
                            <input type="text" maxlength="1024" class="form-control" id="fav-item-note">
                        </div>
                        <div class="form-group">
                            <label class="col-form-label">{% trans "Listes" %}</label>
                        </div>
                        <div class="row" id="fav-list">
                            {% for fav_list in user.fav_lists.all %}
                                <div class="col-12 col-md-6">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">
                                                <input type="checkbox" value="{{ fav_list.id }}">
                                            </div>
                                        </div>
                                        <input type="text" class="form-control" data-toggle-checkbox aria-label="{{ fav_list.name }}" value="{{ fav_list.name }}" readonly>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="d-none">
                            <input type="submit" />
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary btn-knightools-valid" onclick="favorites.save_item();">{% trans "Enregistrer" %}</button>
                    <button type="button" class="btn btn-secondary btn-knightools-cancel" data-dismiss="modal">{% trans "Fermer" %}</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="edit-list" tabindex="-1" role="dialog" aria-labelledby="edit-list-label" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="edit-list-label">{% trans "Modifier une liste de favoris" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="edit-list-form" onsubmit="favorites.save_list(); return false;">
                        <input type="hidden" id="fav-list-id" />
                        <div class="form-group">
                            <label for="fav-list-name" class="col-form-label">{% trans "Nom :" %}</label>
                            <input type="text" maxlength="64" class="form-control" id="fav-list-name">
                        </div>
                        <div class="d-none">
                            <input type="submit" />
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary btn-knightools-valid" onclick="favorites.save_list();">{% trans "Enregistrer" %}</button>
                    <button type="button" class="btn btn-secondary btn-knightools-cancel" data-dismiss="modal">{% trans "Fermer" %}</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="delete-list" tabindex="-1" role="dialog" aria-labelledby="delete-list-label" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="delete-list-label">{% trans "Supprimer une liste de favoris" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="delete-list-form" onsubmit="favorites.rm_list(); return false;">
                        <input type="hidden" id="fav-list-id" />
                        <div class="form-group">
                            <label for="fav-list-item-action" class="col-form-label">{% trans "Que faire des favoris dans cette liste ?" %}</label>
                            <select class="form-control" id="fav-list-item-action">
                                <option value="keep">{% trans "Conserver les favoris et les déplacer dans la liste par défaut si nécessaire" %}</option>
                                <option value="remove-orphan">{% trans "Supprimer les favoris n'étant pas dans une autre liste" %}</option>
                                <option value="remove-completely">{% trans "Supprimer tous les favoris associés, y compris s'ils sont dans d'autres listes" %}</option>
                            </select>
                        </div>
                        <div class="d-none">
                            <input type="submit" />
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" onclick="favorites.rm_list();">{% trans "Supprimer" %}</button>
                    <button type="button" class="btn btn-secondary btn-knightools-cancel" data-dismiss="modal">{% trans "Fermer" %}</button>
                </div>
            </div>
        </div>
    </div>
    <div class="d-none" id="fav-url-manager"
        data-create-list-url=""
        data-delete-list-url="{% url 'users:fav_del_list' %}"
        data-edit-list-url="{% url 'users:fav_edit_list' %}"
        data-order-url="{% url 'users:fav_order_list' %}"
        data-copy-item-url="{% url 'users:fav_copy_item' %}"
        data-edit-item-url="{% url 'users:fav_edit_item' %}"
        data-delete-item-url="{% url 'users:fav_del_item' %}"
    ></div>
{% endblock %}

users/templates/users/favorite_on_item.html
{% load static %}
{% load i18n %}

{% if user.is_authenticated %}
    {% spaceless %}
        <a title="{% if is_favorite %}{% trans 'Retirer des favoris' %}{% else %}{% trans 'Ajouter aux favoris' %}{% endif %}" href="#" class="badge fav-link">
            <i class="{% if is_favorite %}fas{% else %}far{% endif %} fa-star"></i>
        </a>
        <div class="modal fade" id="add-item-to-fav" tabindex="-1" role="dialog" aria-labelledby="add-item-to-fav-label" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="add-item-to-fav-label">{% trans "Ajouter un élément aux favoris" %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="add-item-to-fav-form" onsubmit="favorites.add(); return false;">
                            <input type="hidden" id="fav-item-type" value="{{ type }}" />
                            <input type="hidden" id="fav-item-id" value="{{ id }}" />
                            <div class="form-group">
                                <label for="fav-item-note" class="col-form-label">{% trans "Descriptif (optionnel) :" %}</label>
                                <input type="text" maxlength="1024" class="form-control" id="fav-item-note">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">{% trans "Listes" %}</label>
                            </div>
                            <div class="row" id="fav-list">
                                {% for fav_list in user.fav_lists.all %}
                                    <div class="col-12 col-md-6">
                                        <div class="input-group input-group-sm mb-3">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <input type="checkbox" value="{{ fav_list.id }}">
                                                </div>
                                            </div>
                                            <input type="text" class="form-control" data-toggle-checkbox aria-label="{{ fav_list.name }}" value="{{ fav_list.name }}" readonly>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <button role="button" type="button" id="new-list" class="btn btn-success w-100"><i class="fas fa-plus-circle"></i></button>
                            <div class="d-none">
                                <input type="submit" />
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary btn-knightools-valid" onclick="favorites.add();">{% trans "Enregistrer" %}</button>
                        <button type="button" class="btn btn-secondary btn-knightools-cancel" data-dismiss="modal">{% trans "Fermer" %}</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-none" id="fav-url-manager" data-add-url="{% url 'users:fav_add' %}" data-del-url="{% url 'users:fav_del' %}"></div>
        <script type="text/javascript" src="{% static 'users/js/favorites.js' %}"></script>
    {% endspaceless %}
{% endif %}

users/templates/users/profile.html
{% extends 'users/base.html' %}

{% load static %}
{% load martortags %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load gm_extras %}

{% block title %}{% trans "Profil" %} - {% endblock %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'users/js/account.js' %}"></script>
{% endblock js %}

{% block content %}
<form method="post">
    <h1 class="text-center">{% trans "Vos informations" %}</h1>
    {% csrf_token %}
    <div class="row">
        <div class="col-12">
            <h6>{% trans "Votre compte" %}</h6>
        </div>
        <div class="col">
            {{ form.username|as_crispy_field }}
        </div>
        <div class="col align-bottom">
            {% url "users:change_password" as url_chgpwd %}
            <span class="form-text">
                {% blocktrans trimmed with url_chgpwd=url_chgpwd %}
                    Pour changer votre mot de passe, <a href="{{ url_chgpwd }}">utilisez ce formulaire</a>.
                {% endblocktrans %}
            </span>
        </div>
        <div class="col-12"></div>
        <div class="col">
            {{ form.first_name|as_crispy_field }}
        </div>
        <div class="col">
            {{ form.last_name|as_crispy_field }}
        </div>
        <div class="col-12">
            {{ form.email|as_crispy_field }}
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            <h6>{% trans "Interface" %}</h6>
        </div>
        <div class="col-6">
            {{ form.prechecked_sources|as_crispy_field }}
        </div>
        {% if form.instance.game_master or form.instance.get_next_game_master_question %}
            <div class="col-6">
                {{ form.game_master|as_crispy_field }}
                {% if not form.instance.game_master %}
                    <div class="d-none" id="game-master-question">
                        {{ form.game_master_question|as_crispy_field }}
                    </div>
                {% else %}
                    {% get_current_language as LANGUAGE_CODE %}
                    {% if LANGUAGE_CODE == 'fr' %}
                        {{ form.gest_account|as_crispy_field}}
                    {% endif %}
                {% endif %}
            </div>
        {% endif %}
    </div>
    {% if not form.instance.is_gest_game_master %}
    <div class="row mt-5">
        <div class="col-12">
            <h6>{% trans "Accréditations" %}</h6>
        </div>
        <div class="col">
            {{ form.activation_code|as_crispy_field }}
        </div>
    </div>
    {% endif %}
    <button type="submit" class="btn btn-success">{% trans "Enregistrer" %}</button>
</form>
<hr>
<div class="mb-5">
    <h2 class="text-danger text-center mt-5">{% trans "ZONE DE DANGER" %}</h2>
    <a href="{% url 'users:del_user' %}" class="btn btn-danger">{% trans "Supprimer votre compte" %}</a>
</div>
{% endblock %}