gm/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import misc, calculators, searches, lists, details, prints, faq

app_name = 'gm'
urlpatterns = [
    path('', misc.IndexView.as_view(), name='index'),
    path('about/', misc.AboutView.as_view(), name='about'),
    path('ai_generator/', cache_page(0)(misc.generateAI), name='ai_generator'),
    path('ai_generator/<codename>/', misc.generateAI, name='ai_informations'),
    path('ajax/autocomplete.json', misc.AutocompleteView.as_view(), name='autocomplete'),
    path('ajax/theme', misc.SetTheme.as_view(), name='set_theme'),
    
    path('weapon/', lists.WeaponListView.as_view(), name='weapon_list'),
    path('module/', lists.ModuleListView.as_view(), name='module_list'),
    path('effect/', lists.EffectListView.as_view(), name='effect_list'),
    path('overdrive/', lists.OverdriveListView.as_view(), name='overdrive_list'),
    path('enhancement/', lists.EnhancementListView.as_view(), name='enhancement_list'),
    path('armour/', lists.ArmourListView.as_view(), name='armour_list'),
    path('division/', lists.DivisionListView.as_view(), name='division_list'),
    path('arcana/', lists.ArcanaListView.as_view(), name='arcana_list'),
    path('crest/', lists.CrestListView.as_view(), name='crest_list'),
    path('archetype/', lists.ArchetypeListView.as_view(), name='archetype_list'),
    path('great_deed/', lists.GreatDeedListView.as_view(), name='great_deed_list'),
    path('heroic-ability/', lists.HeroicAbilityListView.as_view(), name='heroic_ability_list'),
    path('vehicle/', lists.VehicleListView.as_view(), name='vehicle_list'),
    path('style/', lists.StyleListView.as_view(), name='style_list'),
    path('trauma/', lists.TraumaListView.as_view(), name='trauma_list'),
    path('mecha/', lists.MechaArmourListView.as_view(), name='mecha_list'),
    path('npc-ability/', lists.NonPlayerCharacterAbilityListView.as_view(), name='npc_ability_list'),
    path('twin_ability/', lists.ArmourTwinAbilityListView.as_view(), name='twin_list'),
    path('ultimate_aptitude/', lists.UltimateAptitudeListView.as_view(), name='ultimate_list'),
    
    path('weapon/<int:pk>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<int:pk>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<int:pk>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<int:pk>/', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<int:pk>/', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/<int:pk>/', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<int:pk>/', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<int:pk>/', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<int:pk>/', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('heroic-ability/<int:pk>/', details.HeroicAbilityDetailView.as_view(), name='heroic_ability_detail'),
    path('vehicle/<int:pk>/', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('trauma/<int:pk>/', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('ultimate_aptitude/<int:pk>/', details.UltimateAptitudeDetailView.as_view(), name='ultimate_detail'),
    
    path('weapon/<slug:slug>/', details.WeaponDetailView.as_view(), name='weapon_detail'),
    path('module/<slug:slug>/', details.ModuleDetailView.as_view(), name='module_detail'),
    path('effect/<slug:slug>/', details.EffectDetailView.as_view(), name='effect_detail'),
    path('overdrive/<slug:slug>/', details.OverdriveDetailView.as_view(), name='overdrive_detail'),
    path('enhancement/<slug:slug>/', details.EnhancementDetailView.as_view(), name='enhancement_detail'),
    path('armour/classified', details.ArmourClassifiedView.as_view(), name='armour_unknown'),
    path('armour/<slug:slug>/', details.ArmourDetailView.as_view(), name='armour_detail'),
    path('division/<slug:slug>/', details.DivisionDetailView.as_view(), name='division_detail'),
    path('arcana/<slug:slug>/', details.ArcanaDetailView.as_view(), name='arcana_detail'),
    path('great_deed/<slug:slug>/', details.GreatDeedDetailView.as_view(), name='great_deed_detail'),
    path('heroic-ability/<slug:slug>/', details.HeroicAbilityDetailView.as_view(), name='heroic_ability_detail'),
    path('archetype/<slug:slug>/', details.ArchetypeDetailView.as_view(), name='archetype_detail'),
    path('crest/<slug:slug>/', details.CrestDetailView.as_view(), name='crest_detail'),
    path('vehicle/<slug:slug>/', details.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('style/<slug:slug>/', details.StyleDetailView.as_view(), name='style_detail'),
    path('trauma/<slug:slug>/', details.TraumaDetailView.as_view(), name='trauma_detail'),
    path('mecha/classified', details.MechaArmourClassifiedView.as_view(), name='mecha_unknown'),
    path('mecha/<slug:slug>/', details.MechaArmourDetailView.as_view(), name='mecha_detail'),
    path('npc-ability/<slug:slug>/', details.NonPlayerCharacterAbilityDetailView.as_view(), name='npc_ability_detail'),
    path('ultimate_aptitude/<slug:slug>/', details.UltimateAptitudeDetailView.as_view(), name='ultimate_detail'),
    
    path('longbow_calculator/', calculators.LongbowCalculatorView.as_view(), name='longbow_calculator'),
    path('weapon-calculator/', calculators.WeaponCalculatorView.as_view(), name='weapon_calculator'),
    
    path('faq/v1/', faq.QuestionV1ListView.as_view(), name='faqv1'),
    path('faq/v1.5/', faq.QuestionV1Dot5ListView.as_view(), name='faqv1.5'),
    
    path('search/', searches.search, name='search'),
    
    path('print/weapon/', prints.WeaponPrintListView.as_view(), name='print_weapon'),
    path('print/module/', prints.ModulePrintListView.as_view(), name='print_module'),
    path('print/overdrive/', prints.OverdrivePrintListView.as_view(), name='print_overdrive'),
    path('print/enhancement/', prints.EnhancementPrintListView.as_view(), name='print_enhancement'),
    path('print/trauma/', prints.TraumaPrintListView.as_view(), name='print_trauma'),
    
    # Retrocomp
    path('skill/', lists.HeroicSkillListRedirectView.as_view(), name='skill_list'),
    path('skill/<int:pk>/', details.HeroicSkillDetailRedirectView.as_view(), name='skill_detail'),
    path('skill/<slug:slug>/', details.HeroicSkillDetailRedirectView.as_view(), name='skill_detail'),
    path('stance/', lists.StanceListRedirectView.as_view(), name='stance_list'),
    path('stance/<slug:slug>/', details.StanceDetailRedirectView.as_view(), name='stance_detail'),
    path('npc_capacity/', lists.NonPlayerCharacterCapacityListRedirectView.as_view(), name='npc_capacity_list'),
    path('npc_capacity/<slug:slug>/', details.NonPlayerCharacterCapacityDetailRedirectView.as_view(), name='npc_capacity_detail'),
    
]

knight_master_overview/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static

from .views import account, martor

urlpatterns = [
    path('camelot/', admin.site.urls),
    path('martor/uploader/', martor.markdown_uploader, name="markdown_uploader_page"),
    path('martor/', include('martor.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('api/', include('api.urls')),
    path('accounts/login/', account.JointLoginSignupView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', include('robots.urls')),
]

gm_urls = ([
    path('', include('gm.urls')),
], 'gm')


virtualtable_urls = ([
    path('', include('virtualtable.urls')),
], 'virtualtable')

urlpatterns += i18n_patterns(
    path('', include('gm.urls')),
    path('virtualtable/', include('virtualtable.urls')),
    path('api/', include('api.urls')),
    path('users/', include('users.urls')),
    prefix_default_language=True
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gm/views/calculators.py
from django.shortcuts import render
from django.views import generic
from django.utils.translation import get_language
from django.db.models import Prefetch

from ..models.weaponry import (
    Weapon, WeaponI18n, ReachI18n, WeaponAttackI18n,
    WeaponAttackEffectI18n
)

class LongbowCalculatorView(generic.View):
    def get(self, request):
        return render(request, 'gm/calculators/longbow.html', {
            "longbow": Weapon.objects.get(slug='fusil-longbow'),
        })

class WeaponCalculatorView(generic.View):
    def get(self, request):
        language = get_language()
        weapons = (
            WeaponI18n
            .objects
            .filter(
                translations__language_code=language,
                calculator=True
            )
            .prefetch_related(
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.filter(
                        calculator_behaviour='INI',
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='initial_attacks'
                ),
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.filter(
                        calculator_behaviour='LST',
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='listing_attacks'
                ),
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.filter(
                        calculator_behaviour='REP',
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='replacement_attacks'
                ),
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.filter(
                        calculator_behaviour='REM',
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='removal_attacks'
                ),
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.filter(
                        calculator_behaviour='RED',
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='reduction_attacks'
                ),
                Prefetch(
                    'attacks',
                    queryset=WeaponAttackI18n.objects.exclude(
                        calculator_behaviour='INI'
                    ).filter(
                        translations__language_code=language,
                        weapon__translations__language_code=language
                    ).order_by('calculator_order_appliance'),
                    to_attr='non_initial_attacks'
                ),
            )
            .all()
        )
        reaches = ReachI18n.objects.filter(translations__language_code=language).all()
        
        return render(request, 'gm/calculators/weapon.html', {
            "weapons": weapons,
            "reaches": reaches
        })
    

gm/views/faq.py
from django.views import generic
from django.db.models import Q, Count, Prefetch
from django.contrib.auth.mixins import LoginRequiredMixin

from ..models.faq import Category, Question, CategoryTreebeardI18n, QuestionI18n

class QuestionV1ListView(generic.ListView):
    template_name = 'gm/faq/list.html'
    context_object_name = 'faq'
    
    def get_context_data(self, **kwargs):
        context = super(QuestionV1ListView, self).get_context_data(**kwargs)
        
        prefetch = Prefetch(
            'questions',
            queryset=Question.objects.filter(v1=True, gm=False).order_by('-created')
        )
        
        if self.request.user.is_authenticated and self.request.user.game_master:
            prefetch = Prefetch(
                'questions',
                queryset=Question.objects.filter(v1=True).order_by('-created')
            )
        
        categories = Category.objects.prefetch_related(prefetch).all()
        displayed_category = []
        index_category = {}
        
        for category in categories:
            index_category[category.id] = len(displayed_category)
            displayed_category.append((category, category.is_leaf_node() and len(category.questions.all()) > 0))
            
            if category.is_leaf_node():
                if len(category.questions.all()) > 0:
                    for ancestor in category.get_ancestors():
                        displayed_category[index_category[ancestor.id]] = (ancestor, True)
        
        context['displayed_categories'] = displayed_category
        
        return context
        
    def get_queryset(self):
        """Return list of weapon."""
        return (Question
            .objects
            .filter(
                v1=True
            )
            .order_by('category', '-created'))

class QuestionV1Dot5ListView(generic.ListView):
    template_name = 'gm/faq/list.html'
    context_object_name = 'faq'
    
    def get_context_data(self, **kwargs):
        context = super(QuestionV1Dot5ListView, self).get_context_data(**kwargs)
        
        prefetch = Prefetch(
            'questions',
            queryset=QuestionI18n.objects.filter(v1_5=True, gm=False).order_by('-created')
        )
        
        if self.request.user.is_authenticated and self.request.user.game_master:
            prefetch = Prefetch(
                'questions',
                queryset=QuestionI18n.objects.filter(v1_5=True).order_by('-created')
            )
        
        categories = CategoryTreebeardI18n.objects.prefetch_related(prefetch).all()
        displayed_category = []
        index_category = {}
        
        for category in categories:
            index_category[category.id] = len(displayed_category)
            displayed_category.append((category, category.is_leaf() and len(category.questions.all()) > 0))
            
            if category.is_leaf():
                if len(category.questions.all()) > 0:
                    for ancestor in category.get_ancestors():
                        displayed_category[index_category[ancestor.id]] = (ancestor, True)
        
        context['displayed_categories'] = displayed_category
        
        return context
        
    def get_queryset(self):
        """Return list of weapon."""
        return (QuestionI18n
            .objects
            .filter(
                v1_5=True
            )
            .order_by('category__translations__name', '-created'))

gm/templates/gm/details/archetype.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Archétype" %} {{ archetype.name }} - {% endblock %}

{% block content %}
    <a href="{% url 'gm:archetype_list' %}"><i class="fas fa-arrow-circle-left"></i> {% trans "Liste des archétypes" %}</a>
    <div class="p-3 my-2">
        <h1 class="text-center font-weight-bold">{{ archetype.name }}</h1>
    </div>
    
    <div class="card-deck">
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans 'Description' %}
                </h5>
            </div>
            <div class="card-body text-justify">
                {{ archetype.description|linebreaks }}
            </div>
        </div>
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans 'Bonus carac.' %}
                </h5>
            </div>
            <div class="card-body text-justify">
                {% if archetype.characteristic_bonus_1 or archetype.characteristic_bonus_2 or archetype.characteristic_bonus_3 %}
                    <ul class="m-0">
                        <li>{{ archetype.characteristic_bonus_1.name }}</li>
                        <li>
                            {{ archetype.characteristic_bonus_2.name }}
                            {% if archetype.characteristic_bonus_3 %}
                                {% blocktrans trimmed with charac_name=archetype.characteristic_bonus_3.name %}
                                    OU {{ charac_name }}
                                {% endblocktrans %}
                            {% endif %}
                        </li>
                    </ul>
                {% else %}
                    {% trans 'Deux différentes au choix, à définir' %}
                {% endif %}
            </div>
        </div>
    </div>
    
    {% if archetype.questions_list %}
        {% include 'gm/misc/faq_text.html' with questions=archetype.questions_list %}
    {% endif %}
{% endblock %}

gm/templates/gm/details/division.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Section" %} {{ division.name }} - {% endblock %}

{% block content %}
    <a href="{% url 'gm:division_list' %}"><i class="fas fa-arrow-circle-left"></i> {% trans "Liste des sections" %}</a>
    <div class="p-3 my-2">
        <h1 class="text-center font-weight-bold">{{ division.name}}</h1>
        <blockquote class="blockquote font-italic text-center text-muted">
            <p>{{ division.motto }}</p>
        </blockquote>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <h5 class="font-weight-bold font-italic mb-0">{% trans "Description" %}</h5>
        </div>
        <div class="card-body markdown-format text-justify">
            {{ division.description|safe_markdown }}
        </div>
    </div>
    <div class="card-deck mb-sm-3">
        {% if division.weapons_list %}
            <div class="card">
                <div class="card-header">
                    <h5 class="font-weight-bold font-italic mb-0">
                        {% blocktrans trimmed count counter=division.weapons_list|length %}
                            Arme offerte
                        {% plural %}
                            Armes offertes
                        {% endblocktrans %}
                    </h5>
                </div>
                <div class="card-body">
                    <ul>
                        {% for weapon_division in division.weapons_list %}
                            <li><a href="{% url 'gm:weapon_detail' weapon_division.weapon.slug %}">[{{ weapon_division.weapon.category.name }}] {{ weapon_division.weapon.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        {% if division.overdrives_list %}
            <div class="card">
                <div class="card-header">
                    <h5 class="font-weight-bold font-italic mb-0">
                        {% blocktrans trimmed count counter=division.overdrives_list|length %}
                            Overdrive offert
                        {% plural %}
                            Overdrives offerts
                        {% endblocktrans %}
                    </h5>
                </div>
                <div class="card-body">
                    <ul>
                        {% for overdrive in division.overdrives_list %}
                            {% with od=overdrive.characteristic.name|slugify|add:'-1' %}
                                <li><a href="{% url 'gm:overdrive_detail' od %}">{{ overdrive.characteristic.name }}</a></li>
                            {% endwith%}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        {% if division.modules_list %}
            <div class="card">
                <div class="card-header">
                    <h5 class="font-weight-bold font-italic mb-0">
                        {% blocktrans trimmed count counter=division.modules_list|length %}
                            Module offert
                        {% plural %}
                            Modules offerts
                        {% endblocktrans %}
                    </h5>
                </div>
                <div class="card-body">
                    <ul>
                        {% for module_division in division.modules_list %}
                            <li>
                                <a href="{% url 'gm:module_detail' module_division.module_level.module.slug %}">
                                    {{ module_division.module_level }}
                                    {% if module_division.forced_choice_effect %}
                                        ({{ module_division.forced_choice_effect }})
                                    {% endif %}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        <div class="card">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans 'Aspect' %}
                </h5>
            </div>
            <div class="card-body">
                {% blocktrans trimmed with aspect=division.aspect_bonus.name %}
                    Augmente 1 point dans l'Aspect <em>{{ aspect }}</em> et 1 point dans chaque caractéristique associée à ce dernier :
                {% endblocktrans %}
                <ul>
                    {% for characteristic in division.aspect_bonus.characteristics.all %}
                        <li>
                            <em>{{ characteristic.name }}</em>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    
    <div class="card mb-3">
        <div class="card-header">
            <h5 class="font-weight-bold font-italic mb-0">
                {% trans 'Inconvénient' %} - {{ division.disadvantage_name }}
            </h5>
        </div>
        <div class="card-body">
            <div class="text-justify markdown-format">{{ division.disadvantage|safe_markdown }}</div>
        </div>
    </div>
    
    {% if division.questions_list %}
        {% include 'gm/misc/faq_text.html' with questions=division.questions_list %}
    {% endif %}
{% endblock %}

gm/templates/gm/details/trauma.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Trauma" %} {{ trauma.name }} - {% endblock %}

{% block content %}
    {% if user.is_authenticated and user.game_master %}
        <a href="{% url 'gm:trauma_list' %}"><i class="fas fa-arrow-circle-left"></i> {% trans "Liste des traumas" %}</a>
    {% else %}
        <a href="{% url 'gm:index' %}">{% trans "Accueil" %}</a>
    {% endif %}
    <div class="p-3 my-2">
        <h1 class="text-center font-weight-bold">{{ trauma.name }}</h1>
        {% if trauma.is_allowed %}
            <h4 class="text-center">
                <span class="badge badge-pill badge-secondary">{{ trauma.category.name }}</span>
                <span class="badge badge-pill badge-secondary">+{{ trauma.category.hop_recovered }} {% trans "PES" %}</span>
                {% if trauma.die_value %}
                    <span class="badge badge-pill badge-secondary">D6 = {{ trauma.die_value }}</span>
                {% endif %}
            </h4>
            {% if trauma.password and user.game_master %}
                <p>{% trans "Mot de passe pour accéder à ce trauma :" %} <span class="font-italic">{{ trauma.password }}</span></p>
            {% endif %}
        {% endif %}
    </div>
    {% if not trauma.is_allowed %}
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans "Pleine santé" %}
                </h5>
            </div>
            <div class="card-body text-justify">
                {% blocktrans trimmed %}
                    Il semblerait que vous n'ayez aucune séquelle. Si vous deviez subir ce trauma, demandez
                    le code d'activation à votre MJ, qui doit l'avoir visible sur cette même page.
                    Une fois le code en votre possession, allez dans votre profil et dans la section "Accréditations",
                    collez le code fourni. Il vous donnera accès au descriptif de ce trauma.
                {% endblocktrans %}
            </div>
        </div>
    {% else %}
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans 'Description' %}
                </h5>
            </div>
            <div class="card-body text-justify">
                <div class="markdown-format">
                    {{ trauma.description|safe_markdown }}
                </div>
            </div>
        </div>
        
        {% if trauma.questions_list %}
            {% include 'gm/misc/faq_text.html' with questions=trauma.questions_list %}
        {% endif %}
    {% endif %}
{% endblock %}

gm/templates/gm/details/ultimate.html
{% extends 'gm/base.html' %}
{% load static %}
{% load martortags %}
{% load i18n %}

{% block title %}{% trans "Capacité ultime" %} {{ ultimate.name }} - {% endblock %}

{% block content %}
    <a href="{% url 'gm:ultimate_list' %}"><i class="fas fa-arrow-circle-left"></i> {% trans "Liste des capacités ultimes" %}</a>
    <div class="p-3 my-2">
        <h1 class="text-center font-weight-bold">{{ ultimate.name }}</h1>
        {% if not ultimate.armour or ultimate.armour in allowed_armours %}
            <h4 class="text-center">
                <span class="badge badge-pill badge-secondary">{{ ultimate.type.name }}</span>
            </h4>
            <blockquote class="blockquote font-italic text-center text-muted">
                <p>{{ ultimate.quote }}</p>
            </blockquote>
        {% endif %}
    </div>
    {% if ultimate.armour and ultimate.armour not in allowed_armours %}
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="font-weight-bold font-italic mb-0">
                    {% trans "Accréditations limitées" %}
                </h5>
            </div>
            <div class="card-body text-justify">
                {% blocktrans trimmed %}
                    Vous n'avez pas les accréditations nécessaires pour visualiser cette capacité ultime.
                    Cela vient du fait que cette capacité est liée à une armure à laquelle vous n'avez pas accès.
                    Vous pouvez demander le code pour débloquer l'armure liée à votre MJ, qui doit l'avoir visible sur la page de l'armure.
                    Une fois le code en votre possession, allez dans votre profil et dans la section "Activation de code",
                    collez le code fourni. Il vous débloquera l'accès à cette capacité ultime.
                {% endblocktrans %}
            </div>
        </div>
    {% else %}
        <div class="card-deck">
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="font-weight-bold font-italic mb-0">
                        {% trans 'Description' %}
                    </h5>
                </div>
                <div class="card-body text-justify markdown-format">
                    {{ ultimate.description|safe_markdown }}
                </div>
            </div>
            
            {% if ultimate.restriction or ultimate.cost or ultimate.activation or ultimate.duration or ultimate.reach %}
                <div class="card mb-3">
                    <div class="card-header">
                        <h5 class="font-weight-bold font-italic mb-0">
                            {% trans 'Données techniques' %}
                        </h5>
                    </div>
                    <div class="card-body text-justify">
                        <table class="table table-sm table-bordered">
                            <tbody class="thead-light">
                                {% if ultimate.restriction %}
                                    <tr>
                                        <th class="text-center align-middle" scope="row">{% trans "Restriction" %}</th>
                                        <td class="text-center align-middle">
                                            {% if ultimate.crest or ultimate.armour %}
                                                <a href="{% if ultimate.crest %}{% url 'gm:crest_detail' ultimate.crest.slug %}{% else %}{% url 'gm:armour_detail' ultimate.armour.slug %}{% endif %}">{{ ultimate.restriction }}</a>
                                            {% else %}
                                                {{ ultimate.restriction }}
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endif %}
                                {% if ultimate.cost %}
                                    <tr>
                                        <th class="text-center align-middle" scope="row">{% trans "Coût" %}</th>
                                        <td class="text-center align-middle">{{ ultimate.cost }}</td>
                                    </tr>
                                {% endif %}
                                {% if ultimate.activation %}
                                    <tr>
                                        <th class="text-center align-middle" scope="row">{% trans "Activation" %}</th>
                                        <td class="text-center align-middle">{{ ultimate.activation }}</td>
                                    </tr>
                                {% endif %}
                                {% if ultimate.duration %}
                                    <tr>
                                        <th class="text-center align-middle" scope="row">{% trans "Durée" %}</th>
                                        <td class="text-center align-middle">{{ ultimate.duration }}</td>
                                    </tr>
                                {% endif %}
                                {% if ultimate.reach %}
                                    <tr>
                                        <th class="text-center align-middle" scope="row">{% trans "Portée" %}</th>
                                        <td class="text-center align-middle">{{ ultimate.reach.name }}{% if ultimate.reach.short_description %}<small class="text-secondary"> - {{ ultimate.reach.short_description }}</small>{% endif %}</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}